data:
  dataset: {name: titanic, samples: 1316, type: public}
  datasetLoadOption: full
  kfold: 1
  mapping:
    age:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    class:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    sex:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    survived:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples: {split: 1, test: 0, training: 1052, validation: 263}
  shuffle: false
model:
  connections:
  - {source: Dropout_1, target: Dense_2}
  - {source: Input_1, target: Dense_1}
  - {source: Dense_2, target: Output_1}
  - {source: Dense_1, target: Dropout_1}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 23
    y: 17
  - args: {}
    class: Output
    name: Output_1
    x: 4
    y: 477
  - args: {activation: relu, output_dim: '100'}
    class: Dense
    name: Dense_1
    x: 26
    y: 141
  - args: {p: '0.3'}
    class: Dropout
    name: Dropout_1
    x: 23
    y: 243
  - args: {activation: softmax, output_dim: '2'}
    class: Dense
    name: Dense_2
    x: 15
    y: 358
params:
  batch_size: 32
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 5
  optimizer: {name: Adadelta}
project: Titanic using DNN (archive)
